FriendsOfTYPO3/frontend_editing

- Configuration/TypoScript/setup.ts
Disabled since all actions in the plugin are uncached
> [TASK] Disable feature requireCHashArgumentForActionArguments

- Resources/Public/Javascript/Editor.js
Simply disables dragstart. Fix for: #111
> [FIX] disables drag and dropping inline icons.

- Classes/Hook/FrontendEditingInitializationHook.php
When GET parameter ID is not set , property ID is missing for wizard items hook
> [BUGFIX] set UID of root page when ?id= missing

- Classes/Service/ContentEditableWrapperService.php
- Documentation/NewContentElements/Index.rst
With default values it's possible to predefine content element fields. Use in case when you need to add a drop zone with custom user function.
> [TASK] made it possible to set default fields for new content element

- Documentation/Development/Hooks/Index.rst
- Resources/Public/JavaScript/Editor.js
Set up link (both internal and external) in CKEditor through FE editor was not possible, because of error
```
Uncaught TypeError: Cannot read property 'document' of null
at Object.LinkBrowser.finalizeFunction (RteLinkBrowser.js:66)
```
> [BUGFIX] fixed JS error when setting link with CKEditor in modal iframe

- Classes/Hook/FrontendEditingInitializationHook.php
- ext_localconf.php
This speeds up the render and the real frontend page will be called and rendered later with query parameter 'frontend_editing=true'
> [BUGFIX] Unset page setup before render the toolbars

- Resources/Public/JavaScript/GUI.js
We save the scroll position only before refreshing the iframe (save/discard changes) and not when browsing the website directly because, in this last case, the user expect the scroll of the page to be on top. For the same reason we remove "scrollTop" from sessionStorage just after getting it.
FIxes: #186
> [FEATURE] Retain scrollbar position after reloading

- Classes/Controller/ReceiverController.php
- Classes/Service/ContentEditableWrapperService.php
- Resources/Public/JavaScript/Crud.js
- Resources/Public/JavaScript/FrontendEditing.js
Additional info about this commit:
1. gridelements hooks to `wizardItemsHook` to add default parameters `tx_gridelements_container` and `tx_gridelements_columns` based on the columns that called the wizard (aka: the position of the button that the editor clicked to start the wizard)
https://github.com/TYPO3-extensions/gridelements/blob/master/Classes/Hooks/WizardItems.php#L315
2. frontend_editing implements the same TYPO3 hook `wizardItemsHook` to generate its CE wizard (the one in the right column of the UI) but, in this case, the editor didn't press any button before the generation of the wizard. But Gridelements hooks there and adds `tx_gridelements_columns=0` as default parameter for every new CE.
3. To make drag&drop to work for gridelements we must create drop zones using …
> [FEATURE] Handle drag&drop of nested CE

- Classes/Controller/ReceiverController.php
$data[$table][$uid] is NULL when using arrows to move elements.
PHP array_merge between NULL and array results NULL and throws error in DataMapProcessor.
This patch avoids this error making sure that $data[$table][$uid] is always an array.
> [BUGFIX] Merge default values with $data array only if set

- Classes/Service/ContentEditableWrapperService.php
- Tests/Unit/EditingPanel/FrontendEditingPanelTest.php
> [BUGFIX] Use already initialized language service $GLOBALS['LANG']

- Classes/Hook/FrontendEditingInitializationHook.php
- Classes/Service/ContentEditableWrapperService.php
- Classes/ViewHelpers/CustomDropZoneViewHelper.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Partials/CustomRecordTab.html
- Resources/Private/Partials/RightBar.html
- Resources/Public/JavaScript/FrontendEditing.js
- Tests/Unit/Fixtures/ContentEditableFixtures.php
- Tests/Unit/ViewHelpers/CustomDropZoneViewHelperTest.php
With this feature, webmaster is allowed to insert directly record into custom configured zone.
For exemple: a webmaster can insert directly news into the news list.
Configuration is done in 2 part:
1. A custom zone is added via "CustomDropZoneViewHelper" in record listing
2. Allowed record are registred in TypoScript as follow
```
plugin.tx_frontendediting{
customRecords{
10{
table = tx_news_domain_model_news
pid = 6
}
}
}
```
The result will be this:
> Custom record insertion in page

- ext_localconf.php
The file userTsConfig.ts was deleted with commit [dc861b8](https://github.com/FriendsOfTYPO3/frontend_editing/commit/dc861b89819eea92c38ff14cc6080f77020ef7fb). Include of file was still there and causes errors/warnings on commandline.
> [BUGFIX] Remove include of non existing userTsConfig.ts file

- Classes/Service/AccessService.php
- Classes/ViewHelpers/ContentEditableViewHelper.php
This fixes a bug when : 
- Some content elements of a page are fetched from another page, which is not editable by the BE user 
- We are using the `core:contentEditable` viewhelper to enable inline editing with fluid_styled_content.
The error displayed in the system log is `Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1437679657: No content edit permission for user 250 on page 3423 | TYPO3\CMS\Backend\Form\Exception\AccessDeniedContentEditException thrown in file /home/typo3/source/typo3_src-8.7.9/typo3/sysext/backend/Classes/Form/FormDataProvider/DatabaseUserPermissionCheck.php in line 134. Requested URL: https://xxxxxx/typo3/index.php?ajaxID=%2Fajax%2Ffrontend-editing%2Feditor-configuration&ajaxToken=50692c64c3ba0d19aa76ea7e5b2848abf44dcbbc&page=4063&table=tt_content&uid=335 …
> [BUGFIX] Don't display inline editing if the CE is read-only

- Classes/Hook/FrontendEditingInitializationHook.php
Hello
When LANG object is initialized in the frontend editing hook, the language of the user is not initialized.
Regards,
Stéphane
> [BUGFIX] User's language not set 

- Classes/ViewHelpers/ContentEditableViewHelper.php
Content editable viewhelper doesn't display the label record at the hover of the edit button.
> [BUGFIX] Content editable viewhelper doesn't display the label of record

- Classes/Service/AccessService.php
- Classes/ViewHelpers/ContentEditableViewHelper.php
When editing content, it must be checked that the
Permission::CONTENT_EDIT is set. Not the Permission::PAGE_EDIT.
To check storage pages too, the page is fetched with
PageRepository->getPage_noCheck.
> [BUGFIX] Right check for editing page content

- Resources/Private/Sass/inline_editing.scss
Make sure that dropzone always display as block
> New content element can only be added to empty page

- Classes/Hook/FrontendEditingInitializationHook.php
- Resources/Public/JavaScript/GUI.js
1. Add global variable flag that determinate if page is running in FE editing mode.
Example usage in custom JS
`
if (typeof window.top.FrontendEditingMode !== 'undefined') {
// Do something
}
`
2. Example of ajax call
```js
function getContent(element) {
var url = "http://" + window.location.hostname + "?type=5";
var editingMode = typeof window.top.FrontendEditingMode !== 'undefined';
if (editingMode) {
url += "frontend_editing=true&no_cache=1";
}
$.ajax({
url: url,
dataType: "html",
success: function (html_content) {
$(element)
.css("display", "none")
.html(html_content)
.fadeIn();
if (editingMode) {
window.top.F.initCustomLoadedContent($(element));
}
}
});
}
getContent('#ajax');
```
> WIP: Update Editor Events for Ajax Content

- Classes/Controller/EditorController.php
- Resources/Public/JavaScript/Editor.js
Fixes #230. Editor configurations for content element fields were fetched in separate requests, one by one. This had a great impact on speed. The configurations are now fetched all together in a single request.
> [FEATURE] Speed improvement when fetching editing configurations

- Configuration/TypoScript/setup.ts
1. Fluid Styled Content adds the logic it needs through 'lib.contentElement'
2. Keep 'lib.fluidContent' for backwards compatibility
> [TASK] add 'stdWrap' settings for 'lib.contentElement'

- Classes/Hook/FrontendEditingInitializationHook.php
Fixes #380, where a missing condition in `FrontendEditingInitializationHook.php` allowed the `VisibilityAspect` to be applied even when Frontend Editing was not enabled.
> [BUGFIX] Hidden pages are now hidden in menus. 

- Classes/Controller/ReceiverController.php
If editing a Site root the DataHandler is loading additional configuration which
may be faulty. So suppress the Exception and continue because the update action is valid
> [BUGFIX] Editing page title of Siteroot fails

- Resources/Public/JavaScript/GUI.js
For example when link clicked redirects to a new URL without "frontend_editing=true" in the query string.
> [BUGFIX] Avoid inception issue on redirects and link clicks

- Classes/Hook/FrontendEditingInitializationHook.php
With this fix the page tree will be shown correctly according to the DB Mounts of an user.
See issue #411
> [BUGFIX] Show page tree according to DB Mounts (#411)

- Classes/Middleware/FrontendEditingAspect.php
Fixes #412, where content elements were not editable or visible if the page was disabled.
> [BUGFIX] Elements on disabled pages are visible and editable

- Classes/Hook/FrontendEditingInitializationHook.php
- Resources/Private/Partials/LeftBar.html
This change makes use of the IconViewHelper to fetch icons delivered
with TYPO3 via its official API.
Where not applicable, the icon configuration is fetched instead to
obtain the icon's source path.
Fixes: #450
> [BUGFIX] Use IconAPI where applicable to fetch Core icons

- Resources/Public/JavaScript/GUI.js
The loading overlay doesn't disappear.
Somehow loadingScreenLevel is zero, but should be one.
> Issue #454 loading won't hide

- Configuration/TypoScript/Compatibility8/setup.ts
- Configuration/TypoScript/setup.ts
Missing "&&" caused in an Expression could not be parsed error.
> [BUGFIX] Fixed incorrect TypoScript conditions

- Classes/ViewHelpers/ContentEditableViewHelper.php
When the ContentEditableViewHelper is used like this:
```html
<core:contentEditable table="tt_content" field="header" uid="{uid}">{header}</core:contentEditable>
```
and the `header` is empty (new content element), it results in a TypeError
> Argument 4 passed to TYPO3\CMS\FrontendEditing\Service\ContentEditableWrapperService::wrapContentToBeEditable() must > be of the type string, null given, called in /var/www/dg/mw/public/typo3conf/ext/frontend_editing/Classes/ViewHelpers/ContentEditableViewHelper.php on line 153
If the `header` is empty, than is `$content` equal `null`. Casting it to string, resolves this issue.
> Fix TypeError caused by ContentEditableViewHelper

- Classes/Hook/FrontendEditingInitializationHook.php
In the current version the CKEditor base path is resolved like this:
`window.CKEDITOR_BASEPATH = 'typo3\/sysext\/rte_ckeditor\/Resources\/Public\/JavaScript\/Contrib\/';`
Which results in wrong JS resource paths:
And a JS error:
Using `PathUtility::getAbsoluteWebPath` instead of `PathUtility::getRelativePathTo` solve this issue.
This relates to #426
> Fix CKEditor base path

- Classes/Controller/EditorController.php
- Resources/Public/JavaScript/Editor.js
- composer.json
When a non-admin user was editing a page with a content element the user was not allowed to edit, a 500 error would be shown. It was caused by an AccessDeniedEditInternalsException (1437687404) within DatabaseUserPermissionCheck.
Fixes #552
> [BUGFIX] Prevent error when editing disallowed CE

- Classes/UserFunc/HtmlParserUserFunc.php
- Configuration/TypoScript/constants.typoscript
- Configuration/TypoScript/setup.typoscript
Add query parameter ''frontend_editing=true'' to all links when editing. This is to prevent so that when a user are navigating the page with a tags, that the top bar disappears.
> [TASK] Add query parameter ''frontend_editing=true'' to all links when editing

- Classes/Controller/FrontendEditingModuleController.php
With the latest bugfix for protocol handling in the FrontendEditingModuleController, iframes in HTTPS powered websites are no longer loaded due to an incorrect url (httpss://abc.com/myPage?frontend_editing=true). The replacement should therefore be made here for both cases (http/https).
> [Bugfix] Check should replace full schema http(s)

- Classes/Service/ContentEditableWrapperService.php
This pull request adds the missing `data-new-url` attribute to custom drop zone and closes the opened tag.
ref #611
> [BUGFIX] Add `data-new-url` attribute to custom drop zone and close opened tag

- Classes/Controller/FrontendEditingModuleController.php
v3.0.23 just displays a blank page for me and I think you mismatched the GET param in commit eac17c475293074bbc149d5a78cff5f844c0911f with the one from v2. Fixing this works for me. Please check and accept, if my assumptions are correct.
> [BUGFIX] Replace usage of old GET param frontend_editing_enabled

- Configuration/TypoScript/setup.typoscript
Removes potential for error messages in PHP 8
> [BUGFIX] Use traverse() in TypoScript conditions

- Classes/Hook/FrontendEditingInitializationHook.php
The value of the constant needed to be less that 30 characters. This is due to the fact that VariableProcessor have a maximum value of 30, otherwise it gets resolveHash gets corrupted.
Fixes: #627
> [BUGFIX] Shorten the value for FRONTEND_EDITING_ALREADY_LOADED

- .gitattributes
Several development-only files must not be distributed when installing this extension using Composer with `prefer-dist` being active. We can skip those files by providing a `.gitattributes` file that contains [`export-ignore`](https://git-scm.com/docs/git-archive#Documentation/git-archive.txt-export-ignore) rules for all development-only files and directories.
> [BUGFIX] Exclude dev-only files from package distribution

- Configuration/TCA/Overrides/sys_template.php
- ext_tables.php
When I run "Check for Broken Extensions" in the install tool or use typo3cms upgrade:prepare I get errors that EXT:frontend_editing is broken: 
> Loading ext_tables.php of extension "frontend_editing" failed
Moving the ExtensionManagementUtility::addStaticFile() call to Configuration/TCAOverrides/sys_template.php fixes this issue.
> [FIX] fix errors on install tool check for broken extensions

- Classes/Controller/EditorController.php
$hasCkeditorConfiguration is always true because $this->rteConfiguration is set to an empty array (not null)
> Fix value of $hasCkeditorConfiguration

- ext_localconf.php
or else every page will return 404 if `$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['enforceValidation'] = true`
> [BUGFIX] Exclude fe_editing_already_loaded from cHash calculations

- Classes/Controller/Event/Handler/BootCompletedEventHandler.php
Crawlers and bots sometimes make request with malformed URI. E.g.:
- https://example.com//example.json" (notice the double slash before example.json)
- https://example.com/:443/favicon.ico
This is to avoid exception in these cases.
> [BUGFIX] Strengthen request URI check

- Classes/Controller/FrontendEditingModuleController.php
- Resources/Public/JavaScript/FrontendEditing.js
- ext_localconf.php
If the BE user never changed the web_view state then `$this->getBackendUser()->uc['moduleData']['web_view']['States']['current']` is null and triggers PHP8 warning.
Also the former behaviour was to display the website maximized but also wrongly select the "Custom" preset. Now it select the "Maximized" preset.
> [BUGFIX] Default to maximized web_view state if BE user never changed it

- Resources/Public/JavaScript/FrontendEditing.js
An old known Chrome bug happens sometimes when the DOM is manipulated on dragStart event and the dragEnd fires immediately. The solution is to add a setTimeout of 10 milliseconds into the handler and manipulate the DOM in that timeout.
Resolves: #680
> [BUGFIX] Manipulate DOM in a setTimeout on dragStart

- Classes/Service/ContentEditableWrapperService.php
- Documentation/ConfigureAndExtend/EmptyColumns/Index.rst
- Resources/Public/JavaScript/FrontendEditing.js
and decode htmlspecialchars in Javascript so the website admin doesn't have to worry to wrap core:customDropZone in templates.
> [TASK] Always wrap defVals of drop zones with htmlspecialchars

- Classes/Service/ContentEditableWrapperService.php
> [BUGFIX] Handle flag icon for CE set with language 'All'

- Classes/Service/ContentEditableWrapperService.php
It was added because TYPO3 v9 had some encoding issue. Now it causes some problems, e.g.:
Having a tag in a CE with a data attribute like:
data-focus-point="{"x":0.5,"y":0.5}"
html_entity_decode transforms it to:
data-focus-point="{"x":0.5,"y":0.5}"
so the value of data-focus-point is just "{", causing incorrect JS behavior.
> [BUGFIX] Remove obsolete html_entity_decode

- Resources/Public/JavaScript/Editor.js
This spacer is needed if there's not enough space between the top of the page and the first editable element to allow the inline actions toolbar of this first editable CE to be visible. Without the spacer, in this use case, the inline actions toolbar is hidden under the module doc header.
The code must be placed in .on('load') of inline_editing.css so the inline actions toolbar has its style applied and its height and position can be retrieved correctly.
Resolves: #728
> [BUGFIX] Dynamically add a spacer to the top of the page
