FriendsOfTYPO3/frontend_editing

- Resources/Private/Partials/RightBar.html
- Resources/Private/Styles/Elements/_TopBar.scss
- Resources/Private/Styles/Partials/_Elements.scss
- Resources/Public/Javascript/FrontendEditing.js
- Resources/Public/Styles/Main.css
Removed extra space from items in top-bar when right-bar and left-bar are open. Fixed javascript bug where it would remove active class from accordion when changing device size.
> Styling fixes

- Resources/Private/Styles/Elements/_TopBar.scss
- Resources/Public/Javascript/FrontendEditing.GUI.js
- Resources/Public/Styles/Main.css
moved ckeditor when leftbar is open
> Cke editor fix

- Classes/Hook/ContentPostProc.php
- Configuration/TypoScript/constants.ts
- Configuration/TypoScript/setup.ts
> [BUGFIX] Use Fluid in a correct manner

- Classes/Utility/ContentEditable/ContentEditableWrapper.php
- Tests/Unit/Fixtures/ContentEditableFixtures.php
- Tests/Unit/Utility/ContentEditable/ContentEditableWrapperTest.php
- circle.yml
Updated / added tests for ContentEditableWrapper, small PSR-2 change, enabled ci builder.
> Enable ci builder

- README.md
> [BUGFIX] Fix link to gitbook

- Resources/Private/Css/Elements/_TopBar.scss
- Resources/Private/Partials/TopBar.html
- Resources/Public/Css/Main.css
> [TASK] Add rounded shape to avatar image

- Classes/Controller/CrudController.php
- Classes/EditingPanel/FrontendEditingPanel.php
- Classes/Utility/ContentEditable/ContentEditableWrapper.php
- Classes/Utility/Integration.php
- Configuration/TypoScript/UserTsConfig/userTsConfig.ts
- Resources/Private/Css/InlineEditing.scss
- Resources/Public/Css/InlineEditing.css
- Resources/Public/Javascript/Editor.js
- Resources/Public/Javascript/FrontendEditing.Crud.js
- Tests/Unit/EditingPanel/FrontendEditingPanelTest.php
- Tests/Unit/Fixtures/ContentEditableFixtures.php
- ext_localconf.php
> Add hide/unhide functionality for inline icons

- Classes/Controller/CrudController.php
- Classes/Utility/Integration.php
- Classes/Utility/RequestPreProcess/CeTable.php
> Add Doctrine query builder to all SQL queries

- Classes/Hook/ContentPostProc.php
- Resources/Private/Templates/Toolbars/Toolbars.html
After adding this, frontend_editing seems to work better in Edge (from eternal loading the iframe to mostly functioning).
> [FIX] Rendered page was missing basic HTML-structure. Static structure added.

- Classes/Hook/FrontendEditingInitializationHook.php
Call wizard items hooks if there are some.
> [TASK] support of wizard items hook

- Resources/Public/JavaScript/FrontendEditing.js
> [BUGFIX] fixed issue for links starting with hash symbol. Fixes #148

- Classes/Controller/EditorController.php
- Resources/Public/JavaScript/Crud.js
- Resources/Public/JavaScript/Editor.js
- Resources/Public/JavaScript/GUI.js
> Fix non ckeditor field

- Classes/Provider/FrontendEditingAvatarProvider.php
- ext_localconf.php
Generate absolute url for image, so it can be found on subpages. Fixes #149
> [BUGFIX] create avatar provider for FE

- Classes/Hook/ContentObjectRendererHook.php
- Classes/Service/AccessService.php
- Classes/Service/ContentEditableWrapperService.php
- ext_localconf.php
Add drop zone for column where no content were found. Fixes #155
> [TASK] implement content renderer hook. 

- Resources/Private/Partials/ContentElementHierarchyTab.html
- Resources/Private/Partials/WizardElementTabs.html
- Resources/Public/JavaScript/GUI.js
1. Remember the last opened accordion
2. Remember the last chosen view list or card
These settings are stored in LocalStorage of the browser.
> [TASK] Right panel (Content panel) improvements

- Classes/Hook/FrontendEditingInitializationHook.php
- Resources/Public/JavaScript/GUI.js
otherwise jquery can't find anything in contents()
> [BUGFIX] set iframe content using innerHtml. 

- Resources/Public/JavaScript/D3IndentedTree.js
> [BUGFIX] set hasChildrenExpanded class on expanded node with children

- Classes/ViewHelpers/CustomDropZoneViewHelper.php
> [BUGFIX] Fix custom drop view helper to prevent exception when fields parameter is omitted

- Documentation/Development/Dependencies/Index.rst
This should be left to the Composer docs, e.g. https://getcomposer.org/doc/00-intro.md
> [TASK] Drop Composer installation instructions

- Classes/Hook/FrontendEditingInitializationHook.php
> [FEATURE] Add possibility to include javascript in to window

- Resources/Public/JavaScript/Editor.js
- Resources/Public/JavaScript/GUI.js
* Initialize content inserted after page initialization (ajax call)
* Allow iframe url update by scripting so when iframe is refreshed we have the right url.
> Handle page element insertion and iframe url update

- Resources/Public/JavaScript/Crud.js
- Resources/Public/JavaScript/Editor.js
If wrapper tag is not div, just edit it as simple text.
CKeditor instance doesn't work on inline elements
> After changing basic.contentEditableWrapperTagName to <span>: Saving not possible

- Classes/Controller/EditorController.php
Provide empty string if field name is null
> WIP: CK-Editor Linkbutton with live-editing doesn't work

- Classes/Hook/FrontendEditingInitializationHook.php
- Resources/Private/Partials/LeftBar.html
- Resources/Public/JavaScript/GUI.js
Respect abs prefix when loading Frontend editing resources
> WIP: Links to files point to root folder

- Classes/Middleware/FrontendEditingAspect.php
- Classes/Middleware/FrontendEditingInitiator.php
- Classes/Utility/FrontendEditingUtility.php
- Configuration/RequestMiddlewares.php
- ext_localconf.php
This fixes #349 and fixes #353
> [BUGFIX] use middleware to set visibility aspect and set displayFieldEditIcons

- Classes/Service/ContentEditableWrapperService.php
> [FEATURE] Support for editing translated content

- composer.json
> [BUGFIX] Updated composer.json makes Packagist work again

- .travis.yml
- Classes/Backend/Controller/ContentElement/NewContentElementController.php
- Classes/Controller/EditorController.php
- Classes/Controller/ReceiverController.php
- Classes/Hook/FrontendEditingInitializationHook.php
- Classes/ViewHelpers/ContentEditableViewHelper.php
- Classes/ViewHelpers/CustomDropZoneViewHelper.php
- Classes/ViewHelpers/SvgViewHelper.php
- Configuration/TypoScript/setup.ts
- Documentation/Installation/Index.rst
- composer.json
- ext_emconf.php
Make frontend editing TYPO3 10 compatible with backwards to functionality to TYPO3 8.7
> [FEATURE] Make frontend editing TYPO3 10 compatible

- Classes/Controller/ReceiverController.php
> [BUGFIX] Error when deleting content element

- Resources/Private/Templates/FluidStyledContent9/Textpic.html
> [BUGFIX] Added Text & Image template

- Classes/Hook/TemplateServiceHook.php
- Configuration/TypoScript/Compatibility8/setup.ts
- ext_localconf.php
Fixes #402
[BUGFIX] Links use correct link format
Fixes #403
> [BUGFIX] Pages showing after editing in frontend

- Resources/Public/JavaScript/Editor.js
- Resources/Public/JavaScript/GUI.js
Implemented count for loading screen show/hide calls, so the loading screen will remain until the last process requiring the loading screen is complete. Also implemented loading screen for configuration processing, so that editor configuration is always set before editing is possible.
> [BUGFIX] Improved loading screen

- Resources/Private/Language/locallang.xlf
- Resources/Public/JavaScript/Editor.js
- Resources/Public/JavaScript/FrontendEditing.js
[TASK] Added arguments to translate function: "Hello, {0}"
> [BUGFIX] User is notified when editor configuration fetch fails

- Resources/Public/JavaScript/Crud.js
- Resources/Public/JavaScript/GUI.js
> [BUGFIX] Loading screen should disappear after save

- Classes/Hook/FrontendEditingInitializationHook.php
Added wanted window.CKEDITOR_BASEPATH and ckeditor.js moved to the footer.
> [BUGFIX] Fix broken CKEditor dependencies

- Resources/Public/JavaScript/GUI.js
> Fix iframe refresh fault

- .eslintrc.json
- package.json
added eslint as npm dev-dependency,
configured eslint as project code style is written and best practise,
changed base files by eslint with --fix as flag
fixes #463
> Using eslint

- Resources/Public/JavaScript/FrontendEditing.js
- Resources/Public/JavaScript/GUI.js
- Resources/Public/JavaScript/Scroller.js
> Scrolling during drag fault

- Classes/Controller/EditorController.php
> [BUGFIX] Make sure that the $queryParameters['elements'] exists

- Classes/Controller/FrontendEditingModuleController.php
- ext_emconf.php
> 453 remove view page

- Documentation/InlineEditing/Index.rst
> [TASK] Add documentation regarding RTE links not parsed

- Resources/Public/JavaScript/Scroller.js
* fixed max scroll rounding fault
* fixed missing last scroll function call
[ADDED] scroller support for regular HTML elements
[ADDED] scroller reload function to reset scroll areas if necessary
> [BUGFIXED] scroller

- ext_localconf.php
> [BUGFIX] Exclude the frontend editing from the cHash calculations

- Resources/Public/JavaScript/Editor.js
> [BUGFIX] Fix issue with that Modal do not stop loading

- Classes/Service/ContentEditableWrapperService.php
- Documentation/BEUserTSconfig/Index.rst
> [TASK] Add possibility to ''Disallow editing for content elements''

- Resources/Public/JavaScript/FrontendEditing.js
Sorry, forgot to change. :grimacing:
> [BUGFIX] scroller initialization

- Resources/Public/JavaScript/Modal.js
fixes #503 #504 
[BUGFIX] change jqueryElement from this to currentModal to trigger dismiss
[BUGFIX] prevent default modal creation since they don't get removed from Modal.instances list
> fixe dismiss problem in Modal

- Resources/Public/JavaScript/Crud.js
- Resources/Public/JavaScript/Modal.js
fix #506 with a workaround empty body check
> 506 error when saving inline editable content

- Classes/Hook/Backend/Template/DocumentTemplate.php
- Resources/Public/JavaScript/PageTree.js
- ext_localconf.php
**Testing**
To test this.
1. First you need to navigate to to the frontend editing backend module
2. Next is to choose a page to edit
3. Edit the page and **do not save** and click another page in the page tree
4. A Modal should now appear looking like the image attached
Test the different scenarios of the buttons.
> 456 prevent exit if not saved

- .github/workflows/ter-release.yml
> [TASK] Add TER release for Github Actions

- Classes/ViewHelpers/ContentEditableViewHelper.php
> [BUGFIX] Add check for if content is null on renderAsTag

- Classes/Core/Html/HtmlParser.php
Add check for if $params['casesensitiveComp'] is set in HtmlParser.
> [BUGFIX] Add check for if $params['casesensitiveComp'] is set in HtmlParser

- Classes/Hook/FrontendEditingInitializationHook.php
> [BUGFIX] Make sure that the cms key is set

- Classes/ViewHelpers/ContentEditableViewHelper.php
> [BUGFIX] Prevent "empty" to be rendered in contentEditableViewHelper

- Classes/Hook/FrontendEditingInitializationHook.php
- Classes/UserFunc/HtmlParserUserFunc.php
- Configuration/TypoScript/constants.typoscript
- Configuration/TypoScript/setup.typoscript
> [TASK] Add userFunc for handling form submissions when editing

- Classes/Service/ContentEditableWrapperService.php
> [BUGFIX] Make sure customDropZone works

- Classes/Controller/FrontendEditingModuleController.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/FrontendEditingModule/Show.html
- composer.json
> [TASK] Other domains

- Classes/Service/ContentEditableWrapperService.php
> [BUGFIX] Add `data-new-url` attribute to custom drop zone

- Documentation/KnownIssues/Index.rst
> [DOC] Document issue regarding Route Enhancers

- Classes/Controller/FrontendEditingModuleController.php
> [BUGFIX] Add case insensitive check for getProtocol

- Resources/Public/JavaScript/ParentWindow.js
- ext_localconf.php
> [BUGFIX] Ensure that it is possible to pick an asset in TCE Form Modal

- Resources/Public/JavaScript/ParentWindow.js
> [BUGFIX] Fix CKEditor links

- Resources/Public/JavaScript/ParentWindow.js
This reverts commit 89e832227269b568e0edbc531760231a707f4b93.
Fixes: #653
> [BUGFIX] "Revert Fix CKEditor links (#652)"

- Classes/Controller/Event/Handler/BootCompletedEventHandler.php
> [BUGFIX] Add check for REQUEST_URI

- Classes/Controller/FrontendEditingModuleController.php
> [BUGFIX] Check that targetUrl exists

- Classes/Service/ContentEditableWrapperService.php
> [BUGFIX] Fix hidden elements issues

- Classes/EditingPanel/FrontendEditingPanel.php
- Classes/Hook/FrontendEditingInitializationHook.php
- Classes/Service/ContentEditableWrapperService.php
- Documentation/NewContentElements/Index.rst
- Resources/Public/JavaScript/Crud.js
- Resources/Public/JavaScript/FrontendEditing.js
> [BUFIX] Use core /record/process ajax route when moving CEs

- Classes/Xclass/ContentObject/ContentObjectRenderer.php
> [TASK] Fix xclass condition

- Classes/EditingPanel/FrontendEditingPanel.php
- Classes/Service/ContentEditableWrapperService.php
> [BUGFIX] Set defVals if a CE is inside a container

- Resources/Public/JavaScript/FrontendEditing.js
This avoid a PHP warning in EXT:container
> [BUGFIX] colPos defaults to 0 if not defined

- Classes/Controller/FrontendEditingModuleController.php
> [BUGFIX] Default preset button label to 'Custom' if not set

- Classes/Controller/ReceiverController.php
- Resources/Private/Language/locallang.xlf
- Resources/Public/JavaScript/Crud.js
Also replace some hard coded messages with translatable messages in ReceiverController.
Resolves: #725
> [TASK] Give more info about locked record

- Classes/Controller/EditorController.php
- Classes/Service/AccessService.php
- Classes/Service/ContentEditableWrapperService.php
- Classes/ViewHelpers/ContentEditableViewHelper.php
> [BUGFIX] Improve handling of edit permissions
